#!/bin/bash

### Source: https://serverfault.com/questions/98745/how-to-repeatedly-call-rsync-until-files-are-sucessfully-transferred
### ABOUT
### Runs rsync, retrying on errors up to a maximum number of tries.
### Simply edit the rsync line in the script to whatever parameters you need.

. $DIR/rbackup.conf

# Trap interrupts and exit instead of continuing the loop
trap "echo Exited!; exit;" SIGINT SIGTERM

MAX_RETRIES=50
i=0

# Set the initial return value to failure
false

while [ $? -ne 0 -a $i -lt $MAX_RETRIES ]
do
 i=$(($i+1))
 if [ -n "$SSHCMD" ]; then
   rsync -e "$SSHCMD" $@
 else
   rsync $@
 fi
done

if [ $i -eq $MAX_RETRIES ]
then
  echo "Hit maximum number of retries, giving up."
fi
